### ISSUE TITLE
Certain hsl values result in NaN in converted stylesheets when converted to oklch

### ISSUE THREAD

**Issue by frank-topel-dbi** [fpetrakov/convert-to-oklch#14]
Input file:

```css
:root {
  --dbi--color--brand-1: hsl(213.3, 14.3%, 87.6%);
  --dbi--color--brand-2: hsl(212.1, 14.9%, 63.1%);
  --dbi--color--brand-3: hsl(213.2, 23.9%, 38.6%);
  --dbi--color--brand-4: hsl(212.1, 23.7%, 23.1%);

  --dbi--color--blue-1: hsl(204.4, 36%, 85.3%);
  --dbi--color--blue-2: hsl(204, 35.4%, 55.7%);
  --dbi--color--blue-3: hsl(203.9, 100%, 26.1%);
  --dbi--color--blue-4: hsl(204, 100%, 15.7%);

  --dbi--color--grey-1: hsl(0, 0%, 93.3%);
  --dbi--color--grey-2: hsl(0, 0%, 86.7%);
  --dbi--color--grey-3: hsl(0, 0%, 73.3%);
  --dbi--color--grey-4: hsl(0, 0%, 40%);
  --dbi--color--grey-5: hsl(0, 0%, 20%);

  --dbi--color--green-1: hsl(150, 22.5%, 84.3%);
  --dbi--color--green-2: hsl(151.2, 21.7%, 52.9%);
  --dbi--color--green-3: hsl(151.7, 79.8%, 21.4%);
  --dbi--color--green-4: hsl(151.2, 78.8%, 12.9%);

  --dbi--color--red-1: hsl(348, 61.4%, 88.8%);
  --dbi--color--red-2: hsl(348, 60.7%, 66.1%);
  --dbi--color--red-3: hsl(348, 79.2%, 43.3%);
  --dbi--color--red-4: hsl(348, 78.9%, 26.1%);

  --dbi--color--brown-1: hsl(0, 20.3%, 74.9%);
  --dbi--color--brown-2: hsl(0, 18.2%, 44.1%);

  --dbi--color--orange-1: hsl(35.5, 100%, 85.1%);
  --dbi--color--orange-2: hsl(36.1, 100%, 67.5%);
  --dbi--color--orange-3: hsl(36, 100%, 50%);
  --dbi--color--orange-4: hsl(36.1, 100%, 30%);

  --dbi--color--purple-1: hsl(330.6, 100%, 90%);
  --dbi--color--purple-2: hsl(329.6, 33.1%, 52%);

  --dbi--color--violet-1: hsl(269.4, 100%, 90%);
  --dbi--color--violet-2: hsl(279.8, 59.8%, 60%);

  --dbi--color--yellow-1: hsl(60, 100%, 84.9%);
  --dbi--color--yellow-2: hsl(47.9, 100%, 60%);

  --dbi--color--black: hsl(0, 0%, 0%);
  --dbi--color--white: hsl(0, 0%, 100%);
}
```

Output file:
```css
:root {
  --dbi--color--brand-1: oklch(90.2% 0.008 253.8);
  --dbi--color--brand-2: oklch(70% 0.027 251.9);
  --dbi--color--brand-3: oklch(48.2% 0.049 254.1);
  --dbi--color--brand-4: oklch(34.3% 0.031 252.3);

  --dbi--color--blue-1: oklch(88.6% 0.023 237.6);
  --dbi--color--blue-2: oklch(65.1% 0.071 238.5);
  --dbi--color--blue-3: oklch(42% 0.11 247);
  --dbi--color--blue-4: oklch(29.9% 0.075 244.8);

  --dbi--color--grey-1: oklch(94.9% 0 NaN);
  --dbi--color--grey-2: oklch(89.8% 0 NaN);
  --dbi--color--grey-3: oklch(79.2% 0 NaN);
  --dbi--color--grey-4: oklch(51% 0 NaN);
  --dbi--color--grey-5: oklch(32.1% 0 NaN);

  --dbi--color--green-1: oklch(89.1% 0.023 164.5);
  --dbi--color--green-2: oklch(66.5% 0.067 163.1);
  --dbi--color--green-3: oklch(43.8% 0.102 155.9);
  --dbi--color--green-4: oklch(31.2% 0.069 156.8);

  --dbi--color--red-1: oklch(89.2% 0.04 4.4);
  --dbi--color--red-2: oklch(68.4% 0.132 8.5);
  --dbi--color--red-3: oklch(53.1% 0.202 19);
  --dbi--color--red-4: oklch(36.9% 0.137 17.6);

  --dbi--color--brown-1: oklch(78.6% 0.03 17.8);
  --dbi--color--brown-2: oklch(51.8% 0.054 19.1);

  --dbi--color--orange-1: oklch(92.1% 0.068 76.9);
  --dbi--color--orange-2: oklch(84.1% 0.138 75.1);
  --dbi--color--orange-3: oklch(77.2% 0.174 64.6);
  --dbi--color--orange-4: oklch(53.2% 0.118 66.5);

  --dbi--color--purple-1: oklch(89.7% 0.066 347.5);
  --dbi--color--purple-2: oklch(58.2% 0.116 349.6);

  --dbi--color--violet-1: oklch(88.2% 0.074 307.1);
  --dbi--color--violet-2: oklch(62.1% 0.19 312.8);

  --dbi--color--yellow-1: oklch(98.2% 0.097 108.1);
  --dbi--color--yellow-2: oklch(88.6% 0.17 93.6);

  --dbi--color--black: oklch(0% 0 NaN);
  --dbi--color--white: oklch(100% 0 NaN);
}
```
